### ISSUE TITLE
NoClassDefFoundError on Java 10 (Java 9 untested)

### ISSUE THREAD

**Issue by trainphreak** [EngineHub/SquirrelID#8]
Calls to HttpRepositoryService.findByName() result in a NoClassDefFoundError due to the javax.xml.bind no longer being part of the default library in Java 10 (possibly also on Java 9, I haven't checked).

```
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
    at com.sk89q.squirrelid.util.HttpRequest.returnContent(HttpRequest.java:234) ~[?:?]
    at com.sk89q.squirrelid.resolver.HttpRepositoryService.query(HttpRepositoryService.java:168) ~[?:?]
    at com.sk89q.squirrelid.resolver.HttpRepositoryService.findAllByName(HttpRepositoryService.java:141) ~[?:?]
    at com.sk89q.squirrelid.resolver.HttpRepositoryService.findByName(HttpRepositoryService.java:120) ~[?:?]
```

**Comment by sk89q** [comment]
It's the same error on 9. I will look into it this week.

**Comment by me4502** [comment]
Fixed.
